#ifndef IMG_H
#define IMG_H
#include "include.h"


//*************** Irudiak menu ****************
#define IRUDIA_MENU_HASIJOKOA ".\\img\\menu\\hasi-jokoa.bmp"
#define IRUDIA_MENU_PUNTUAZIOA ".\\img\\menu\\puntuazioa.bmp"
#define IRUDIA_MENU_ITXIJOKOA ".\\img\\menu\\itxi-jokoa.bmp"
#define IRUDIA_MENU_PAUSAJARRAITU ".\\img\\menu\\pausa-jarraitu.bmp"
#define IRUDIA_MENU_PAUSAMENU ".\\img\\menu\\pausa-menu.bmp"
#define IRUDIA_MENU_IDATZIIZENA ".\\img\\menu\\idatzi-izena.bmp"
#define IRUDIA_MENU_PUNTUAZIOABISTARATU ".\\img\\menu\\puntuazioa-bistaratu.bmp"
//************* Irudiak minijokoa ****************
#define IRUDIA_MAPA_1 ".\\img\\menu\\minijokoa\\mapa-1.bmp"
#define IRUDIA_MAPA_2 ".\\img\\menu\\minijokoa\\mapa-2.bmp"
#define IRUDIA_MINIJOKOA_PERTSONAIA_IBAY ".\\img\\menu\\minijokoa\\ibay.bmp"
#define IRUDIA_MINIJOKOA_PERTSONAIA_NAIRU ".\\img\\menu\\minijokoa\\nairu.bmp"
#define IRUDIA_MINIJOKOA_PERTSONAIA_THALIEL ".\\img\\menu\\minijokoa\\thaliel.bmp"
#define IRUDIA_MINIJOKOA_PERTSONAIA_TRYDAN ".\\img\\menu\\minijokoa\\trydan.bmp"
#define IRUDIA_MINIJOKOA_MINIDOWN_1 ".\\img\\menu\\minijokoa\\mini-down-1.bmp"
#define IRUDIA_MINIJOKOA_MINIDOWN_2 ".\\img\\menu\\minijokoa\\mini-down-2.bmp"
#define IRUDIA_MINIJOKOA_MINIDOWN_3 ".\\img\\menu\\minijokoa\\mini-down-3.bmp"
#define IRUDIA_MINIJOKOA_MINIUP_1 ".\\img\\menu\\minijokoa\\mini-up-1.bmp"
#define IRUDIA_MINIJOKOA_MINIUP_2 ".\\img\\menu\\minijokoa\\mini-up-2.bmp"
#define IRUDIA_MINIJOKOA_MINIUP_3 ".\\img\\menu\\minijokoa\\mini-up-3.bmp"
#define IRUDIA_MINIJOKOA_MINIRIGHT_1 ".\\img\\menu\\minijokoa\\mini-right-1.bmp"
#define IRUDIA_MINIJOKOA_MINIRIGHT_2 ".\\img\\menu\\minijokoa\\mini-right-2.bmp"
#define IRUDIA_MINIJOKOA_MINIRIGHT_3 ".\\img\\menu\\minijokoa\\mini-right-3.bmp"
#define IRUDIA_MINIJOKOA_MINILEFT_1 ".\\img\\menu\\minijokoa\\mini-left-1.bmp"
#define IRUDIA_MINIJOKOA_MINILEFT_2 ".\\img\\menu\\minijokoa\\mini-left-2.bmp"
#define IRUDIA_MINIJOKOA_MINILEFT_3 ".\\img\\menu\\minijokoa\\mini-left-3.bmp"
#define IRUDIA_MINIJOKOA_KREDITUAK ".\\img\\menu\\minijokoa\\kredituak.bmp"
#define IRUDIA_MINIJOKOA_LAGUNTZA ".\\img\\menu\\minijokoa\\laguntza.bmp"

//****************** Irudiak background ****************
#define IRUDIA_ESZENA_BORROKA_1 ".\\img\\background\\borroka-1.bmp"
#define IRUDIA_ESZENA_GAMEOVER ".\\img\\background\\gameover.bmp"
#define BUKAERA_IMAGE ".\\img\\background\\gameover.bmp"
#define IRUDIA_TENPORIZADOREA ".\\img\\background\\tenporizadorea.bmp"

//**************** Irudiak pertsonaiak ****************
//FAY
#define IRUDIA_PERTSONAIA_FAY_ATAQUE_1L ".\\img\\pertsonaiak\\fay\\fay-ataque-1L.bmp"
#define IRUDIA_PERTSONAIA_FAY_ATAQUE_1R ".\\img\\pertsonaiak\\fay\\fay-ataque-1R.bmp"
#define IRUDIA_PERTSONAIA_FAY_ATAQUE_2L ".\\img\\pertsonaiak\\fay\\fay-ataque-2L.bmp"
#define IRUDIA_PERTSONAIA_FAY_ATAQUE_2R ".\\img\\pertsonaiak\\fay\\fay-ataque-3R.bmp"

//IBAY
#define IRUDIA_PERTSONAIA_IBAY_ATAQUE_1 ".\\img\\pertsonaiak\\ibay\\ibay-ataque-1.bmp"
#define IRUDIA_PERTSONAIA_IBAY_ATAQUE_2 ".\\img\\pertsonaiak\\ibay\\ibay-ataque-2.bmp"
#define IRUDIA_PERTSONAIA_IBAY_NORMAL_1 ".\\img\\pertsonaiak\\ibay\\ibay-normal-1.bmp"
#define IRUDIA_PERTSONAIA_IBAY_NORMAL_2 ".\\img\\pertsonaiak\\ibay\\ibay-normal-2.bmp"
#define IRUDIA_PERTSONAIA_IBAY_CAMINAR_1 ".\\img\\pertsonaiak\\ibay\\ibay-caminar-1.bmp"
#define IRUDIA_PERTSONAIA_IBAY_CAMINAR_2 ".\\img\\pertsonaiak\\ibay\\ibay-caminar-2.bmp"
#define IRUDIA_PERTSONAIA_IBAY_CAMINAR_3 ".\\img\\pertsonaiak\\ibay\\ibay-caminar-3.bmp"
#define IRUDIA_PERTSONAIA_IBAY_CAMINAR_4 ".\\img\\pertsonaiak\\ibay\\ibay-caminar-4.bmp"
#define IRUDIA_PERTSONAIA_IBAY_SALTO_1 ".\\img\\pertsonaiak\\ibay\\ibay-salto-1.bmp"
#define IRUDIA_PERTSONAIA_IBAY_SALTO_2 ".\\img\\pertsonaiak\\ibay\\ibay-salto-2.bmp"
//NAIRU
#define IRUDIA_PERTSONAIA_NAIRU_ATAQUE_1 ".\\img\\pertsonaiak\\nairu\\nairu-ataque-1.bmp"
#define IRUDIA_PERTSONAIA_NAIRU_ATAQUE_2 ".\\img\\pertsonaiak\\nairu\\nairu-ataque-2.bmp"
#define IRUDIA_PERTSONAIA_NAIRU_ATAQUE_3 ".\\img\\pertsonaiak\\nairu\\nairu-ataque-3.bmp"
#define IRUDIA_PERTSONAIA_NAIRU_NORMAL_1 ".\\img\\pertsonaiak\\nairu\\nairu-normal-1.bmp"
#define IRUDIA_PERTSONAIA_NAIRU_NORMAL_2 ".\\img\\pertsonaiak\\nairu\\nairu-normal-2.bmp"
#define IRUDIA_PERTSONAIA_NAIRU_CAMINAR_1 ".\\img\\pertsonaiak\\nairu\\nairu-caminar-1.bmp"
#define IRUDIA_PERTSONAIA_NAIRU_CAMINAR_2 ".\\img\\pertsonaiak\\nairu\\nairu-caminar-2.bmp"
#define IRUDIA_PERTSONAIA_NAIRU_CAMINAR_3 ".\\img\\pertsonaiak\\nairu\\nairu-caminar-3.bmp"
#define IRUDIA_PERTSONAIA_NAIRU_SALTO_1 ".\\img\\pertsonaiak\\nairu\\nairu-salto-1.bmp"
//THALIEL
#define IRUDIA_PERTSONAIA_THALIEL_ATAQUE_1 ".\\img\\pertsonaiak\\thaliel\\thaliel-ataque-1.bmp"
#define IRUDIA_PERTSONAIA_THALIEL_ATAQUE_2 ".\\img\\pertsonaiak\\thaliel\\thaliel-ataque-2.bmp"
#define IRUDIA_PERTSONAIA_THALIEL_CAMINAR_1 ".\\img\\pertsonaiak\\thaliel\\thaliel-caminar-1.bmp"
#define IRUDIA_PERTSONAIA_THALIEL_CAMINAR_2 ".\\img\\pertsonaiak\\thaliel\\thaliel-caminar-2.bmp"
#define IRUDIA_PERTSONAIA_THALIEL_NORMAL_1 ".\\img\\pertsonaiak\\thaliel\\thaliel-normal-1.bmp"
#define IRUDIA_PERTSONAIA_THALIEL_NORMAL_2 ".\\img\\pertsonaiak\\thaliel\\thaliel-normal-2.bmp"
#define IRUDIA_PERTSONAIA_THALIEL_SALTO_1 ".\\img\\pertsonaiak\\thaliel\\thaliel-salto-1.bmp"

//TRYDAN
#define IRUDIA_PERTSONAIA_TRYDAL_ATAQUE_1L ".\\img\\pertsonaiak\\trydan\\trydan-ataque-1L.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_ATAQUE_1R ".\\img\\pertsonaiak\\trydan\\trydan-ataque-1R.bmp"
#define IRUDIA_PERTSONAIA_TRYDAL_ATAQUE_2L ".\\img\\pertsonaiak\\trydan\\trydan-ataque_2L.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_ATAQUE_2R ".\\img\\pertsonaiak\\trydan\\trydan-ataque-2R.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_ATAQUE_3R ".\\img\\pertsonaiak\\trydan\\trydan-ataque-3R.bmp"
#define IRUDIA_PERTSONAIA_TRYDAL_ATAQUE_3L ".\\img\\pertsonaiak\\trydan\\trydan-ataque_3L.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_CAMINAR_1L ".\\img\\pertsonaiak\\trydan\\thaliel-caminar-1L.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_CAMINAR_1R ".\\img\\pertsonaiak\\trydan\\thaliel-caminar-1R.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_CAMINAR_2L ".\\img\\pertsonaiak\\trydan\\thaliel-caminar-2L.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_CAMINAR_2R ".\\img\\pertsonaiak\\trydan\\thaliel-caminar-2R.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_NORMAL_1L ".\\img\\pertsonaiak\\trydan\\thaliel-normal-1L.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_NORMAL_1R ".\\img\\pertsonaiak\\trydan\\thaliel-normal-1R.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_NORMAL_2L ".\\img\\pertsonaiak\\trydan\\thaliel-normal-2L.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_NORMAL_2R ".\\img\\pertsonaiak\\trydan\\thaliel-normal-2R.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_SALTO_1L ".\\img\\pertsonaiak\\trydan\\thaliel-salto-1L.bmp"
#define IRUDIA_PERTSONAIA_TRYDAN_SALTO_1R ".\\img\\pertsonaiak\\trydan\\thaliel-salto-1R.bmp"

//ELEMENTUAK
#define IRUDIA_ELEMENTUA_BITZITZA1 ".\\img\\elementuak\\bizitza-1.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA2L ".\\img\\elementuak\\bizitza-2-eskuma.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA3L ".\\img\\elementuak\\bizitza-3-eskuma.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA4L ".\\img\\elementuak\\bizitza-4-eskuma.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA5L ".\\img\\elementuak\\bizitza-5-eskuma.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA6L ".\\img\\elementuak\\bizitza-6-eskuma.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA7 ".\\img\\elementuak\\bizitza-7.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA2R ".\\img\\elementuak\\bizitza-2-ezkerra.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA3R ".\\img\\elementuak\\bizitza-3-ezkerra.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA4R ".\\img\\elementuak\\bizitza-4-ezkerra.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA5R ".\\img\\elementuak\\bizitza-5-ezkerra.bmp"
#define IRUDIA_ELEMENTUA_BIZITZA6R ".\\img\\elementuak\\bizitza-6-ezkerra.bmp"
#define IRUDIA_PROFILA_FAY_1R  ".\\img\\elementuak\\fay-eskuma.bmp"
#define IRUDIA_PROFILA_FAY_1L  ".\\img\\elementuak\\fay-ezkerra.bmp"
#define IRUDIA_PROFILA_IBAY_1R  ".\\img\\elementuak\\ibay-eskuma.bmp"
#define IRUDIA_PROFILA_IBAY_1L  ".\\img\\elementuak\\ibay-ezkerra.bmp"
#define IRUDIA_PROFILA_NAIRU_1R  ".\\img\\elementuak\\nairu-eskuma.bmp"
#define IRUDIA_PROFILA_NAIRU_1L  ".\\img\\elementuak\\nairu-ezkerra.bmp"
#define IRUDIA_PROFILA_THALIEL_1R  ".\\img\\elementuak\\thaliel-eskuma.bmp"
#define IRUDIA_PROFILA_THALIEL_1L  ".\\img\\elementuak\\thaliel-ezkerra.bmp"
#define IRUDIA_PROFILA_TRYDAN_1R  ".\\img\\elementuak\\trydan-eskuma.bmp"
#define IRUDIA_PROFILA_TRYDAN_1L  ".\\img\\elementuak\\trydan-ezkerra.bmp"
#endif // !IMG_H
